"""FutureStockList table added

Revision ID: 09067fddd2a7
Revises: 629623f22bf1
Create Date: 2023-03-16 18:46:31.388135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09067fddd2a7'
down_revision = '629623f22bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_stock_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_name', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('tv_symbol', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('future_stock_list')
    # ### end Alembic commands ###
