"""watchlist table created

Revision ID: 0b9fc4edaddf
Revises: de298d227b41
Create Date: 2023-03-14 12:18:04.145901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9fc4edaddf'
down_revision = 'de298d227b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('stocks_name', sa.Text(), nullable=False),
    sa.Column('buy_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    # ### end Alembic commands ###
