"""price rename to entry_price

Revision ID: 4f34866337cd
Revises: db26a0d6737b
Create Date: 2023-03-26 19:45:49.237838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f34866337cd'
down_revision = 'db26a0d6737b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('entry_price', sa.Float(), nullable=False))
        # batch_op.drop_column('price')
        batch_op.alter_column(column_name='price',
                              new_column_name='entry_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        # batch_op.drop_column('entry_price')
        batch_op.alter_column(column_name='entry_price',
                              new_column_name='price')

    # ### end Alembic commands ###
