"""added stock_list column

Revision ID: 629623f22bf1
Revises: 0b9fc4edaddf
Create Date: 2023-03-14 13:00:47.623387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629623f22bf1'
down_revision = '0b9fc4edaddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('stock_id', sa.Text(), nullable=False))
        batch_op.drop_column('stocks_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stocks_name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('stock_id')
        batch_op.drop_column('stock_name')

    # ### end Alembic commands ###
