"""new columns added in live_data

Revision ID: 94e80f378b53
Revises: c6d808f51b01
Create Date: 2023-03-30 19:43:05.215441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e80f378b53'
down_revision = 'c6d808f51b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('high', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('low', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('close', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('time_frame', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_data', schema=None) as batch_op:
        batch_op.drop_column('time_frame')
        batch_op.drop_column('volume')
        batch_op.drop_column('close')
        batch_op.drop_column('low')
        batch_op.drop_column('high')
        batch_op.drop_column('open')

    # ### end Alembic commands ###
