"""time_frame column added to Signal

Revision ID: b97072a2b59b
Revises: 4f34866337cd
Create Date: 2023-03-26 20:36:18.530845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97072a2b59b'
down_revision = '4f34866337cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_frame', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('time_frame')

    # ### end Alembic commands ###
