"""rename data_feed to symbol

Revision ID: c6d808f51b01
Revises: 6fc711fbc0de
Create Date: 2023-03-30 19:22:39.574791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d808f51b01'
down_revision = '6fc711fbc0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_data', schema=None) as batch_op:
        batch_op.alter_column(column_name='data_feed',
                              new_column_name='symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_data', schema=None) as batch_op:
        batch_op.alter_column(column_name='symbol',
                              new_column_name='data_feed')

    # ### end Alembic commands ###
