"""First Migrations

Revision ID: d758495e059e
Revises: 
Create Date: 2023-03-10 13:04:42.809365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd758495e059e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_feed', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swing_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('stocks_name', sa.Text(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('buy_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swing_trade')
    op.drop_table('live_data')
    # ### end Alembic commands ###
