"""signal_type column added to Signals

Revision ID: db26a0d6737b
Revises: fada3d80399a
Create Date: 2023-03-16 21:29:45.270203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db26a0d6737b'
down_revision = 'fada3d80399a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_type', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('signal_type')

    # ### end Alembic commands ###
