"""added quantity column

Revision ID: de298d227b41
Revises: 077b9cf0bcc0
Create Date: 2023-03-10 14:43:34.771893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de298d227b41'
down_revision = '077b9cf0bcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swing_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swing_trade', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
