"""Signals table created

Revision ID: fada3d80399a
Revises: 09067fddd2a7
Create Date: 2023-03-16 20:52:18.817348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fada3d80399a'
down_revision = '09067fddd2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    # ### end Alembic commands ###
